name: Generate Art

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC   
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy

    - name: Generate art
      run: python generate_art.py

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A  # This will add all new folders and files
        git commit -m "Add new artwork for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push

